// <auto-generated />
namespace Sem_2_Swimclub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editing));
        
        string IMigrationMetadata.Id
        {
            get { return "202107031710377_editing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
