// <auto-generated />
namespace Sem_2_Swimclub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class roles_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roles_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202106291358379_roles_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
